/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif']
      },
      colors: {
        "surface-dim": "#dadada",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "on-tertiary-container": "#838487",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c9",
        "surface-container": "#eeeeee",
        "on-secondary-fixed-variant": "#46464e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e2e2e5",
        "tertiary-container": "#1a1c1e",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "secondary-fixed": "#e3e1ec",
        "outline-variant": "#cfc4c5",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "inverse-primary": "#c6c6c6",
        "primary-fixed-dim": "#c6c6c6",
        "surface": "#f9f9f9",
        "on-error-container": "#93000a",
        "primary-container": "#1b1b1b",
        "surface-container-low": "#f3f3f4",
        "on-tertiary-fixed-variant": "#454749",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "error": "#ba1a1a",
        "secondary-container": "#e3e1ec",
        "secondary": "#5d5e66",
        "on-surface-variant": "#4c4546",
        "primary": "#000000",
        "on-primary-container": "#848484",
        "background": "#f9f9f9",
        "tertiary": "#000000",
        "on-tertiary-fixed": "#1a1c1e",
        "secondary-fixed-dim": "#c6c5cf",
        "outline": "#7e7576",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-container": "#63646c",
        "on-secondary-fixed": "#1a1b22",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#5e5e5e"
      },
      spacing: {
        "xs": "4px",
        "base": "8px",
        "xl": "80px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "gutter": "24px",
        "container-margin": "64px"
      },
      fontSize: {
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "600"}],
        "display": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}